config/routes.rb
require 'sidekiq/web'

Wljk::Application.routes.draw do
  root to: 'users#welcome'

  devise_for :users

  devise_scope :user do
    get "/signup" => "devise/registrations#new"
    get "/signin" => "devise/sessions#new"
    get "/signout" => "devise/sessions#destroy"
  end

  constraint = lambda { |request| request.env['warden'].authenticate!({ scope: :user }) }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  match "/home" => "users#index", as: :user_home

  resources :users

  resources :mail_templates

end

app/models/mail_template.rb
class MailTemplate < ActiveRecord::Base
  attr_accessible :content, :user_id, :subject

  has_many :mail_recipients, dependent: :destroy
  has_many :recipients, through: :mail_recipients
  has_many :schedule_occurrences, dependent: :destroy, foreign_key: 'scheduled_entity_id'
  has_one :mail_schedule, dependent: :destroy


  accepts_nested_attributes_for :recipients, :mail_recipients
  attr_accessible :recipients_attributes

  accepts_nested_attributes_for :mail_schedule
  attr_accessible :mail_schedule_attributes

  belongs_to :user

  after_create :create_next_occurrence

  # Reference: http://stackoverflow.com/questions/4252349/rail-3-where-condition-using-not-null
  scope :with_schedule, joins(:mail_schedule).where(mail_schedules: { datetime: MailSchedule.arel_table[:datetime].not_eq(nil) })

  def is_scheduled?
    self.mail_schedule.present?
  end

  def is_recurring?
    (self.is_scheduled? and self.mail_schedule.recurring)
  end

  def to_s
    description = ""
    if is_scheduled?
      mail_schedule = self.mail_schedule
      start_datetime = mail_schedule.datetime
      description = "MailTemplate(##{self.id}) scheduled to be sent starting at #{start_datetime}"

      if is_recurring?
        recurring_interval = mail_schedule.recurring_interval
        recurring_interval_type = mail_schedule.recurring_interval_type
        description << " recurring every #{recurring_interval} #{recurring_interval_type}."
        next_scheduled_occurrence = self.schedule_occurrences.due.order('schedule_occurrences.next_occurrence ASC').first.next_occurrence
        description << "Next occurrence is scheduled at: #{next_scheduled_occurrence}"
      end
    else
      description = "Unscheduled MailTemplate(##{self.id})"
    end
    description
  end

  def self.create_mail_template(subject, content, recipients_str, schedule_info_hash, user_id)
    mail_template_attrs = create_mail_template_attrs_hash(subject, content, recipients_str, schedule_info_hash, user_id)

    mail_template = nil
    if required_details_available?(mail_template_attrs)
      existing_recipients_email_arr = segregate_existing_and_new_recipients(mail_template_attrs).first
      mail_template = MailTemplate.create(mail_template_attrs)

      unless existing_recipients_email_arr.empty?
        mail_template.recipients << Recipient.where(email: existing_recipients_email_arr)
      end
    else
      Rails.logger.debug "Could not create MailTemplate.Required values for attributes #{required_attributes} not found."
    end

    mail_template
  end

  def update_mail_template(subject, content, recipients_str, schedule_info_hash)
    updated_mail_template_attrs = MailTemplate.create_mail_template_attrs_hash(subject, content, recipients_str, schedule_info_hash, self.user.id)

    if MailTemplate.required_details_available?(updated_mail_template_attrs)

      # Deleting current mail_recipients associations for mail
      MailRecipient.delete(self.mail_recipients.collect { |mr| mr.id })

      existing_recipients_email_arr = MailTemplate.segregate_existing_and_new_recipients(updated_mail_template_attrs).first

      self.update_attributes(updated_mail_template_attrs)

      unless existing_recipients_email_arr.empty?
        self.recipients << Recipient.where(email: existing_recipients_email_arr)
      end
    else
      Rails.logger.debug "Could not update Mail[id: #{self.id}].Required values for attributes #{MailTemplate.required_attributes} not found."
    end
  end

  def create_next_occurrence
    if self.is_scheduled?
      scheduled_datetime = self.mail_schedule.datetime

      if scheduled_datetime < Time.now.utc
        # Send it now
        BulkMailer.delay.general_mail(self.id)
      else
        create_schedule_occurrence(scheduled_datetime)
      end
    end
  end

  def create_schedule_occurrence(next_occurrence)
    ScheduleOccurrence.create(next_occurrence: next_occurrence, scheduled_entity_id: self.id, occurrence_status: 'due')
  end

  private

  def self.required_attributes
    [ :subject, :content, :recipients_attributes, :user_id ]
  end

  def self.required_details_available?(attrs_hash)
    available_attributes = attrs_hash.keys
    if ( (required_attributes - available_attributes).empty? )
      return true
    end
    return false
  end

  def self.create_mail_template_attrs_hash(subject, content, recipients_str, schedule_info_hash, user_id)
    mail_template_attrs = {}
    mail_template_attrs[:subject] = subject if subject.present?
    mail_template_attrs[:content] = content if content.present?

    add_recipients(recipients_str, mail_template_attrs)
    mail_template_attrs[:mail_schedule_attributes] = Hash[schedule_info_hash] if schedule_info_hash.present?
    mail_template_attrs[:user_id] = user_id if user_id.present?
    mail_template_attrs
  end

  def self.add_recipients(recipients_str, mail_template_attrs)
    if recipients_str.present?
      emails_arr = Recipient.csv_to_emails_arr(recipients_str)
      mail_template_attrs[:recipients_attributes] = emails_arr.collect { |email| { email: email } }
    end
  end

  def self.segregate_existing_and_new_recipients(mail_template_attrs)
    emails_arr = emails_from_recipients_attributes(mail_template_attrs)
    segregated_recipients = Recipient.segregate_existing_and_new_recipients(emails_arr)
    existing_recipients_email_arr = segregated_recipients.first
    # A must step, else duplicate recipients shall get created in RECIPIENTS
    # table when Mail instance is created/updated
    remove_existing_recipient_emails_from_attrs(existing_recipients_email_arr, mail_template_attrs)

    new_recipients_email_arr = segregated_recipients.last

    [ existing_recipients_email_arr, new_recipients_email_arr ]
  end

  def self.emails_from_recipients_attributes(mail_template_attrs)
    mail_template_attrs[:recipients_attributes].collect { |hash| hash[:email] }
  end

  def self.remove_existing_recipient_emails_from_attrs(existing_recipients_email_arr, mail_template_attrs)
    # Remove existing recipients emails from mail_template_attrs[:recipients_attributes]
    # list
    unless existing_recipients_email_arr.empty?
      mail_template_attrs[:recipients_attributes].delete_if { |hash| existing_recipients_email_arr.include?(hash[:email]) }
    end
  end

end

app/controllers/mail_templates_controller.rb
class MailTemplatesController < ApplicationController
  before_filter :require_user

  before_filter :set_active, only: [ :index, :new, :edit ]
  before_filter :find_mail_template, only: [ :show, :edit, :update, :destroy ]

  #GET  /mail_templates(.:format)
  def index
    @existing_mail_templates = current_user.mail_templates
    #send_scheduled_mail(@existing_mail_templates.first) #TODO
  end

  #GET  /mail_templates/new(.:format)
  def new
  end

  #GET  /mail_templates/:id/edit(.:format)
  def edit
  end

  #GET /mail_templates/:id(.:format)
  def show
  end

  #POST /mail_templates(.:format)
  def create
    MailTemplate.create_mail_template(params[:subject], params[:mail_content], params[:recipients], schedule_info_hash, current_user.id)
    redirect_to mail_templates_path
  end

  #PUT /mail_templates/:id(.:format)
  def update
    @mail_template.update_mail_template(params[:subject], params[:mail_content], params[:recipients], schedule_info_hash)
    #redirect_to mail_templates_path(@mail_template) TODO redirect to show action
    redirect_to mail_templates_path
  end

  #DELETE /mail_templates/:id(.:format)
  def destroy
    @mail_template.destroy
    redirect_to mail_templates_path, notice: 'Successfully deleted mail template.'
  end

  private

  def set_active
    @schedule_emails_active = true
  end

  def find_mail_template
    @mail_template = MailTemplate.find_by_id(params[:id])
  end

  def schedule_info_hash
    hash = {}
    scheduleDateTime = params[:scheduleDateTime]
    hash[:datetime] = scheduleDateTime.to_datetime if scheduleDateTime.present?

    if hash[:datetime].present?
      recurring_interval = params[:recurring_interval]
      recurring_interval_type = params[:recurring_interval_type]
      if (recurring_interval.present? and recurring_interval_type.present?)
        recurring_interval_int = recurring_interval.to_i
        if recurring_interval_int > 0
          hash[:recurring] = true
          hash[:recurring_interval] = recurring_interval_int
          hash[:recurring_interval_type] = recurring_interval_type
        else
          Rails.logger.debug "Recurring interval value found <= 0"
        end
      else
        Rails.logger.debug "Recurring interval value and Recurring interval type found missing."
      end
    else
      Rails.logger.debug "Schedule datetime found missing."
    end
    hash
  end

  def send_scheduled_mail(mail_template)
    error_msg = nil
    if mail_template.present?
      id = mail_template.id
      subject = mail_template.subject
      mail_schedule = mail_template.mail_schedule
      begin
        BulkMailer.general_mail(mail_template).deliver
        mail_sent = true
      rescue Exception => e
        error_msg = "Exception occured while trying to send mail."
        error_msg << "MailTemplate details[ id: #{id}, subject: #{subject}] "
        if mail_schedule.present?
          error_msg << "scheduled at #{mail_schedule.formatted_datetime} #{mail_schedule.formatted_recurring_message}"
        end
        error_msg << ".Technical cause: #{e.to_s}"
        mail_sent = false
      end
    else
      error_msg = 'Could not send email.MailTemplate object found nil.'
    end

    Rails.logger.debug "Error occuring while sending mail: #{error_msg}}" if error_msg.present?
    Rails.logger.debug "Mail sent: #{mail_sent}}"
  end


end

app/helpers/mail_templates_helper.rb
module MailTemplatesHelper
end

app/views/mail_templates/_mail_template_form.html.haml
- content_for :additional_styles do
  - hallo_rte_stylesheets = %w(jquery-ui.min font-awesome.min)
  - hallo_rte_additional_stylesheets = %w(jQuery.divPlaceholder)
  - other_stylesheets = %w(bootstrap-datetimepicker.min mail)
  - stylesheets = hallo_rte_stylesheets + hallo_rte_additional_stylesheets + other_stylesheets
  - stylesheets.each do |ss|
    = stylesheet_link_tag(ss, media: "all")

- content_for :additional_scripts do
  - hallo_rte_js = %w(jquery jquery-ui.min rangy-core hallo)
  - hallo_rte_additional_js = %w(jQuery.divPlaceholder)
  - app_required_js = %w(jquery_ujs bootstrap.min bootstrap-dropdown)
  - other_js = %w(date bootstrap-datetimepicker.min jquery.validate.min mail)
  - javascripts = hallo_rte_js + hallo_rte_additional_js + app_required_js + other_js
  - javascripts.each do |js|
    = javascript_include_tag(js)

- url = mail_templates_path
- action_method = :post
- subject = nil
- mail_content = nil
- recipients_str = nil
- schedule_datetime = nil
- is_recurring_schedule = false
- recurring_interval = nil
- recurring_interval_type = 'hours'

- showRecurringDetailsContainer = false

- if @mail_template.present?
  - mail_template_obj = @mail_template
  - url = mail_template_path(mail_template_obj)
  - action_method = :put
  - subject = mail_template_obj.subject
  - mail_content = mail_template_obj.content
  - recipients_str = mail_template_obj.recipients.collect { |recipient| recipient.email }.join(', ')
  - mail_schedule = mail_template_obj.mail_schedule
  - if mail_schedule.present?
    - schedule_datetime_format = '%d/%m/%Y %H:%M:%S'
    - schedule_datetime = mail_schedule.datetime.strftime(schedule_datetime_format)
    - is_recurring_schedule = mail_schedule.recurring
    - if is_recurring_schedule
      - showRecurringDetailsContainer = true
      - recurring_interval = mail_schedule.recurring_interval
      - recurring_interval_type = mail_schedule.recurring_interval_type

= form_tag(url, method: action_method, class: 'form-horizontal', id: 'scheduleMailForm') do
  .control-group
    = text_field_tag('subject', subject, class: 'input-xxlarge required', placeholder: 'Write in your mail subject here.')

  .control-group
    - if mail_content.present?
      #currentMailContent(style='display:none;')
        = mail_content.html_safe

    -# Hallo JS doesn't work with content under <textarea> tag.Thus simulating a textarea using CSS.
    -# References:
    -#  1. http://stackoverflow.com/questions/10133783/how-can-i-change-cols-of-textarea-in-twitter-bootstrap
    -#  2. https://github.com/sprucemedia/jQuery.divPlaceholder.js#readme
    -#  3. http://stackoverflow.com/questions/8956567/how-do-i-make-an-editable-div-look-like-a-text-field
    -#  4. https://github.com/bergie/hallo#readme
    #textarea.richTextEditor.editable(data-placeholder='Write in your content, select text using mouse and format.')
    = hidden_field_tag "mail_content"

  .control-group
    = text_area_tag('recipients', recipients_str, rows: 5, class: 'input-xlarge', placeholder: "Input/Paste here recipients' email address separated by comma." )

  .control-group
    = label_tag('Schedule Datetime')
    .well
      -# References:
      -# 1. http://tarruda.github.com/bootstrap-datetimepicker/
      -# 2. http://www.eyecon.ro/bootstrap-datepicker/
      %div(id='mailScheduleDateTime' class='input-append date datetimepicker')
        -# Reference: http://stackoverflow.com/questions/3329961/jquery-can-i-validate-a-disabled-field
        -# Default value should be in the same format specified by data-format attribute, else
        -# JS error: TypeError: this._date is null occurs.
        = text_field_tag('scheduleDateTime', schedule_datetime, :"data-format" => "dd/MM/yyyy hh:mm:ss", readonly: "readonly")
        %span.add-on
          %i(data-time-icon="icon-time" data-date-icon="icon-calendar")

      &nbsp;&nbsp;&nbsp;

      %span{ id:'clearDateTime', style: "#{schedule_datetime.present? ? '' : 'display:none' }" }
        = link_to('#') do
          %i.icon-remove

  .control-group
    = label_tag('', class: 'checkbox') do
      = check_box_tag('recurring_schedule', 1, is_recurring_schedule, id: 'recurring_schedule_cbox', disabled: !is_recurring_schedule)
      Recurring

  .control-group{ style: "#{showRecurringDetailsContainer ? '' : 'display:none' }",  id: 'recurringScheduleDetailsContainer' }
    .input-prepend
      %span.add-on Every
      = text_field_tag('recurring_interval', recurring_interval, class: 'span2 input-mini')
      - options = options_for_select([ ['Minutes', 'minutes'], ['Hours', 'hours'], ['Days', 'days'], ['Months', 'months'], ['Years', 'years'] ], recurring_interval_type)
      = select_tag('recurring_interval_type', options)

  .control-group
    = submit_tag('Save', class: 'btn btn-primary')
    = link_to('Cancel', mail_templates_path, class: 'btn btn-primary')

app/views/mail_templates/edit.html.haml
%h2 Edit mail!

= render partial: "mail_template_form"

app/views/mail_templates/index.html.haml
- content_for :additional_styles do
  - stylesheets = %w(mail)
  - stylesheets.each do |ss|
    = stylesheet_link_tag(ss, media: "all")

.container
  %br/
  = button_to('New Mail Template', new_mail_template_path, { form_class: 'form-inline', class: 'btn btn-primary', method: :get })

- if @existing_mail_templates.present?
  %table.table.table-striped.table-bordered
    %thead
      %tr
        %th Subject
        %th Scheduled At
        %th Recurring
        %th Actions

    %tbody
      - @existing_mail_templates.each do |mail_template|
        - mail_schedule = mail_template.mail_schedule
        %tr
          %td<
            = link_to(mail_template.subject, mail_template_path(mail_template))
          - if mail_schedule.present?
            %td= mail_schedule.formatted_datetime
            %td= mail_schedule.formatted_recurring_message
          - else
            %td= 'Not scheduled yet!'
            %td= 'NA'
          %td
            %span<
              = link_to(edit_mail_template_path(mail_template)) do
                %i.icon-edit
            %span(style='padding-left: 5px; padding-right: 5px;')<
              |
            %span<
              = link_to(mail_template_path(mail_template), method: :delete, confirm: 'Are your sure?') do
                %i.icon-remove

app/views/mail_templates/new.html.haml
%h2 Schedule an email!

= render partial: "mail_template_form"

app/views/mail_templates/show.html.haml
.container
  %br/
  %dl.dl-horizontal
    %dt= "Content"
    %dd= @mail_template.content.html_safe

    %br/

    %dt= "Recipients"
    %dd
      %ul.unstyled
        - @mail_template.recipients.each do |recipient|
          %li= recipient.email

    - mail_schedule = @mail_template.mail_schedule
    - if mail_schedule.present?
      %br/
      %dt= "Scheduled At"
      %dd= mail_schedule.formatted_datetime

      - if mail_schedule.recurring
        %br/
        %dt= "Recurring"
        %dd= mail_schedule.formatted_recurring_message

  -#.span2.offset2
  .form-actions
    = link_to('Back', mail_templates_path, class: 'btn btn-primary')
    = link_to('Edit', edit_mail_template_path(@mail_template), class: 'btn btn-primary')