config/routes.rb
require 'sidekiq/web'

Wljk::Application.routes.draw do
  root to: 'users#welcome'

  devise_for :users

  devise_scope :user do
    get "/signup" => "devise/registrations#new"
    get "/signin" => "devise/sessions#new"
    get "/signout" => "devise/sessions#destroy"
  end

  constraint = lambda { |request| request.env['warden'].authenticate!({ scope: :user }) }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  match "/home" => "users#index", as: :user_home

  resources :users

  resources :mail_templates

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :mail_templates, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user, except: [:welcome]

  def welcome
  end

  def index
    @home_active = true
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_links.haml
-# if controller_name != 'sessions'
  = link_to "Sign in", signin_path
  %br/
-# if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", signup_path
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/