config/routes.rb
require 'sidekiq/web'

Wljk::Application.routes.draw do
  root to: 'users#welcome'

  devise_for :users

  devise_scope :user do
    get "/signup" => "devise/registrations#new"
    get "/signin" => "devise/sessions#new"
    get "/signout" => "devise/sessions#destroy"
  end

  constraint = lambda { |request| request.env['warden'].authenticate!({ scope: :user }) }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  match "/home" => "users#index", as: :user_home

  resources :users

  resources :mail_templates

end

app/views/layouts/_flash_messages.html.haml
.flash_messages_container
  - flash.each do |name, message|
    - css_class = ''
    - case name
      - when :error
        - css_class = 'error'
      - when :alert
        - css_class = 'alert'
      - when :notice
        - css_class = 'notice'

    %p{class: css_class}= message

app/views/layouts/_navigation.html.haml
.navbar.navbar-static-top
  .navbar-inner
    =link_to "Logo", user_home_path, class: "brand"

    %ul.nav
      - if user_signed_in?
        %li{ class: "#{@home_active ? 'active' : ''}" }
          =link_to "Home", user_home_path
        %li{ class: "#{@schedule_emails_active ? 'active' : ''}" }
          =link_to "Schedule Emails", mail_templates_path
      %li
        =link_to "Link", "#"

    %ul.nav.pull-right
      - if user_signed_in?
        %li= link_to('Sign out', signout_path)
      - else
        %li.dropdown
          = link_to '#', class: "dropdown-toggle", :"data-toggle" => "dropdown" do
            Join/Enter
            %b.caret

          %ul.dropdown-menu
            %li= link_to('Sign in', signin_path)
            %li= link_to('Sign Up', signup_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title WLJK
    = stylesheet_link_tag    "application", media: "all"
    = yield :additional_styles
    = yield :additional_scripts
    = javascript_include_tag "application" unless content_for?(:additional_scripts)
    = csrf_meta_tags
  %body
    .container
      = render partial: "layouts/navigation"

      = yield